services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    depends_on:
      - database
    volumes:
      - ./site:/var/www/
    environment:
      - DB_HOST=database
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_PORT=${DATABASE_PORT}
    expose:
      - "9000"

  nginx:
    image: nginx:latest
    container_name: app-webserver
    volumes:
      - ./site:/var/www/
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - "${NGINX_PORT}:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: app-phpmyadmin
    depends_on:
      - database
    ports: 
      - "${PHPMYADMIN_PORT}:80"
    environment:
      - PMA_HOST=database
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  database:
    image: mariadb:latest
    container_name: app-database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_PORT=${DATABASE_PORT}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/data:/var/lib/mysql
